// WorkSpace — course maps (verbatim from spec Appendix 13.1, this school's catalog).
// For multi-school (Phase 6) these become per-schoolDomain config.

export const COURSE_COLORS: Record<string, string> = {
  'English Language Arts': '#e091a8',
  'Enriched Geometry': '#f0c040',
  'Social Studies': '#e05050',
  Science: '#9b7ec8',
  Tanach: '#2a4d8e',
  Ivrit: '#70c0e0',
  "Torah She'b'al Peh": '#6abf69',
  Art: '#e08060',
  'Computer Science': '#e08060',
  Music: '#e08060',
  PE: '#a0a0a0',
  Coding: '#ff1493',
  Film: '#9ca3af',
  Claude: '#9ca3af',
  Misc: '#9ca3af',
};

export const COURSE_ABBR: Record<string, string> = {
  ela: 'English Language Arts',
  english: 'English Language Arts',
  eng: 'English Language Arts',
  la: 'English Language Arts',
  'language arts': 'English Language Arts',
  'lang arts': 'English Language Arts',
  math: 'Enriched Geometry',
  geo: 'Enriched Geometry',
  geometry: 'Enriched Geometry',
  geom: 'Enriched Geometry',
  sost: 'Social Studies',
  social: 'Social Studies',
  ss: 'Social Studies',
  socstud: 'Social Studies',
  soc: 'Social Studies',
  history: 'Social Studies',
  hist: 'Social Studies',
  sci: 'Science',
  science: 'Science',
  bio: 'Science',
  chem: 'Science',
  phys: 'Science',
  tanach: 'Tanach',
  tan: 'Tanach',
  torah: 'Tanach',
  tanakh: 'Tanach',
  chumash: 'Tanach',
  ivrit: 'Ivrit',
  hebrew: 'Ivrit',
  heb: 'Ivrit',
  ivr: 'Ivrit',
  toshba: "Torah She'b'al Peh",
  tsbp: "Torah She'b'al Peh",
  tosh: "Torah She'b'al Peh",
  'oral torah': "Torah She'b'al Peh",
  mishna: "Torah She'b'al Peh",
  art: 'Art',
  arts: 'Art',
  studio: 'Art',
  cs: 'Computer Science',
  compsci: 'Computer Science',
  comp: 'Computer Science',
  coding: 'Coding',
  code: 'Coding',
  cod: 'Coding',
  cd: 'Coding',
  programming: 'Coding',
  prog: 'Coding',
  dev: 'Coding',
  film: 'Film',
  fi: 'Film',
  claude: 'Claude',
  ci: 'Claude',
  cl: 'Claude',
  music: 'Music',
  mus: 'Music',
  misc: 'Misc',
  miscellaneous: 'Misc',
};

export const COURSE_TABGROUP_COLOR: Record<string, string> = {
  'English Language Arts': 'pink',
  'Enriched Geometry': 'yellow',
  'Social Studies': 'red',
  Science: 'purple',
  Tanach: 'blue',
  Ivrit: 'cyan',
  "Torah She'b'al Peh": 'green',
  Art: 'orange',
  'Computer Science': 'orange',
  Music: 'orange',
  PE: 'grey',
  Film: 'grey',
  Claude: 'grey',
  Misc: 'grey',
};

export const DEFAULT_COURSE_COLOR = '#9ca3af';
